#logging:
#    level:
#        root: DEBUG

server:
    port: 8081
spring:
    application:
        name: caocao-web
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/xxl_job?serverTimezone=Hongkong&characterEncoding=utf-8&useSSL=false
        username: root
        password: Wsj13191867918
    cloud:
        consul:
            discovery:
                serviceName: ${spring.application.name}
            host: localhost
            port: 8500
            heartbeat:
                enabled: true

feign:
    hystrix:
        enabled: true
