##consul
#spring:
#  cloud:
#    consul:
#      host: localhost
#      port: 8500
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full